### ISSUE TITLE
[Bug] Unzip error

### ISSUE THREAD

**Issue by df13954** [pumPCin/HMAL#1]
### Steps to reproduce/复现步骤

HMAL-V4.0.r23-release.zip，Kitsune 27001.

### Expected behaviour/预期行为

刷入模块成功

### Actual behaviour/实际行为

![screen_cap_20240524_111545](https://github.com/pumPCin/HMAL/assets/18607031/323ea191-1b59-4842-be26-278c3d39da27)

### Xposed Module List/Xposed 模块列表

```Shell
HMA
```

### Magisk Module List/Magisk 模块列表

```Shell
zLSP 7035
```

### HMAL version/HMAL 版本

4.0.r23

### Android version/Android 版本

12

### Magisk version/Magisk 版本

27001

### Version requirement/版本要求

Public release/beta version/公开发布/测试版

### Logs/日志

无

**Comment by L-i-H-u-a** [comment]
смеяться

**Comment by pumPCin** [comment]
its

> ### Steps to reproduce/复现步骤
> HMAL-V4.0.r23-release.zip，Kitsune 27001.
> 
> ### Expected behaviour/预期行为
> 刷入模块成功
> 
> ### Actual behaviour/实际行为
> ![screen_cap_20240524_111545](https://private-user-images.githubusercontent.com/18607031/333431583-323ea191-1b59-4842-be26-278c3d39da27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjM3NjcsIm5iZiI6MTcxNjU2MzQ2NywicGF0aCI6Ii8xODYwNzAzMS8zMzM0MzE1ODMtMzIzZWExOTEtMWI1OS00ODQyLWJlMjYtMjc4YzNkMzlkYTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE1MTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmQ0ZmNkNDM1YjMyMGEwNDE2NjBhMWUyNmRjMmEzNjZmMmM1MDViMWJlZmI3NGM4YWQzNGJkZTQxNmU0YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSiuMwb88XTunIrbjjP7jS91-K_AubsGqDhkIRWNKWY)
> 
> ### Xposed Module List/Xposed 模块列表
> ```shell
> HMA
> ```
> 
> ### Magisk Module List/Magisk 模块列表
> ```shell
> zLSP 7035
> ```
> 
> ### HMAL version/HMAL 版本
> 4.0.r23
> 
> ### Android version/Android 版本
> 12
> 
> ### Magisk version/Magisk 版本
> 27001
> 
> ### Version requirement/版本要求
> Public release/beta version/公开发布/测试版
> 
> ### Logs/日志
> 无

this is not a magisk module, app apk inside zip archive
